id: ID5391FF2
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-6fc9
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 13:04:02.802544+00:00
last_modified: 2023-09-28 13:04:02.802551+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3420
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3420
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིགས་པའི་ཐིགས་པའི་འགྲེལ་པའི་སྟོད་ཆ་དང་སྨད་ཆ།
  languages:
  - bo
  author: པཎྜི་ཏ་ཆོས་མཆོག
statistics:
  ocr_word_mean_confidence_index: 0.9153353832782873
  ocr_word_median_confidence_index: 0.97777152
bases:
  I1NLM3420_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3420_001
      total_pages: 188
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3420_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.97777152
      ocr_word_mean_confidence_index: 0.9153353832782873
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
